// Mocks generated by Mockito 5.4.4 from annotations
// in frendly/test/features/auth/data/repositories/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;

import 'package:frendly/core/services/connectivity/network_info.dart' as _i8;
import 'package:frendly/features/auth/data/datasources/auth_datasource.dart'
    as _i3;
import 'package:frendly/features/auth/data/models/auth_api_model.dart' as _i2;
import 'package:frendly/features/auth/data/models/auth_hive_models.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthApiModel_0 extends _i1.SmartFake implements _i2.AuthApiModel {
  _FakeAuthApiModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IAuthDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthDatasource extends _i1.Mock implements _i3.IAuthDatasource {
  MockIAuthDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> register(_i5.AuthHiveModels? model) => (super.noSuchMethod(
        Invocation.method(
          #register,
          [model],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i5.AuthHiveModels?> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i5.AuthHiveModels?>.value(),
      ) as _i4.Future<_i5.AuthHiveModels?>);

  @override
  _i4.Future<_i5.AuthHiveModels?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i5.AuthHiveModels?>.value(),
      ) as _i4.Future<_i5.AuthHiveModels?>);

  @override
  _i4.Future<bool> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isEmailExist(String? email) => (super.noSuchMethod(
        Invocation.method(
          #isEmailExist,
          [email],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [IAuthRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthRemoteDatasource extends _i1.Mock
    implements _i3.IAuthRemoteDatasource {
  MockIAuthRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AuthApiModel> register(_i2.AuthApiModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [model],
        ),
        returnValue: _i4.Future<_i2.AuthApiModel>.value(_FakeAuthApiModel_0(
          this,
          Invocation.method(
            #register,
            [model],
          ),
        )),
      ) as _i4.Future<_i2.AuthApiModel>);

  @override
  _i4.Future<_i2.AuthApiModel?> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.AuthApiModel?>.value(),
      ) as _i4.Future<_i2.AuthApiModel?>);

  @override
  _i4.Future<String> uploadPhoto(_i6.File? photo) => (super.noSuchMethod(
        Invocation.method(
          #uploadPhoto,
          [photo],
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #uploadPhoto,
            [photo],
          ),
        )),
      ) as _i4.Future<String>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i8.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
